---
- name: Installing Nginx server
  hosts: workshop
  become: true
  tasks: 
    - name: Latest Nginx Web Server
      apt: 
        name: nginx
        state: latest
    - name: Ensure Nginx is enabled and running
      service: 
        name: nginx
        enabled: true 
        state: started
    - name: Installing index file (index.html)
      copy:
        src: index.html
        dest: /var/www/html/index.html